config/routes.rb
Rails.application.routes.draw do
  resources :usages
  resources :recipes
  resources :ingredients
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
		validates :name, {uniqueness: true}
		has_many :usages
		has_many :recipes, through: :usages		
end

app/models/recipe.rb
class Recipe < ApplicationRecord
		validates :name, {uniqueness: true}
		has_many :usages
		has_many :ingredients, through: :usages
end

app/models/usage.rb
#An ingredient that is used in a recipe. Note that we have no concept of 'quantity needed'.
class Usage < ApplicationRecord
	belongs_to :recipe
	belongs_to :ingredient
	validates :recipe_id,{uniqueness: {scope: :ingredient_id}}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception unless Rails.env.test?
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]

  # GET /ingredients
  def index
    @ingredients = Ingredient.all
  end

  # GET /ingredients/1
  def show
  end

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new
  end

  # GET /ingredients/1/edit
  def edit
  end

  # POST /ingredients
  def create
    @ingredient = Ingredient.new(ingredient_params)

    if @ingredient.save
      redirect_to @ingredient, notice: 'Ingredient was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /ingredients/1
  def update
    if @ingredient.update(ingredient_params)
      redirect_to @ingredient, notice: 'Ingredient was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /ingredients/1
  def destroy
    @ingredient.destroy
    redirect_to ingredients_url, notice: 'Ingredient was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def ingredient_params
      params.require(:ingredient).permit(:name, :in_stock)
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  def create
    @recipe = Recipe.new(recipe_params)

    if @recipe.save
      redirect_to @recipe, notice: 'Recipe was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /recipes/1
  def update
    if @recipe.update(recipe_params)
      redirect_to @recipe, notice: 'Recipe was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /recipes/1
  def destroy
    @recipe.destroy
    redirect_to recipes_url, notice: 'Recipe was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def recipe_params
      params.require(:recipe).permit(:name, :process, :url)
    end
end

app/controllers/usages_controller.rb
class UsagesController < ApplicationController
  before_action :set_usage, only: [:show, :edit, :update, :destroy]

  # GET /usages
  def index
    @usages = Usage.all
  end

  # GET /usages/1
  def show
  end

  # GET /usages/new
  def new
    @usage = Usage.new
  end

  # GET /usages/1/edit
  def edit
  end

  # POST /usages
  def create
    @usage = Usage.new(usage_params)

    if @usage.save
      redirect_to @usage, notice: 'Usage was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /usages/1
  def update
    if @usage.update(usage_params)
      redirect_to @usage, notice: 'Usage was successfully updated.'
    else
      puts "**** #{@usage.errors.full_messages} *** #{@usage.recipe_id} #{@usage.ingredient_id} r #{Recipe.all.collect(&:id)} i  #{Ingredient.all.collect(&:id)}"
      render :edit
    end
  end

  # DELETE /usages/1
  def destroy
    @usage.destroy
    redirect_to usages_url, notice: 'Usage was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usage
      @usage = Usage.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def usage_params
      params.require(:usage).permit(:recipe_id, :ingredient_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/usages_helper.rb
module UsagesHelper
end

app/views/ingredients/_form.html.erb
<%= form_with(model: ingredient, local: true) do |form| %>
  <% if ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
      <% ingredient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :ingredient_name %>
  </div>

  <div class="field">
    <%= form.label :in_stock %>
    <%= form.check_box :in_stock, id: :ingredient_in_stock %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ingredients/edit.html.erb
<h1>Editing Ingredient</h1>

<%= render 'form', ingredient: @ingredient %>

<%= link_to 'Show', @ingredient %> |
<%= link_to 'Back', ingredients_path %>

app/views/ingredients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ingredients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>In stock</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ingredients.each do |ingredient| %>
      <tr>
        <td><%= ingredient.name %></td>
        <td><%= ingredient.in_stock %></td>
        <td><%= link_to 'Show', ingredient %></td>
        <td><%= link_to 'Edit', edit_ingredient_path(ingredient) %></td>
        <td><%= link_to 'Destroy', ingredient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ingredient', new_ingredient_path %>

app/views/ingredients/new.html.erb
<h1>New Ingredient</h1>

<%= render 'form', ingredient: @ingredient %>

<%= link_to 'Back', ingredients_path %>

app/views/ingredients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ingredient.name %>
</p>

<p>
  <strong>In stock:</strong>
  <%= @ingredient.in_stock %>
</p>

<%= link_to 'Edit', edit_ingredient_path(@ingredient) %> |
<%= link_to 'Back', ingredients_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kitchenrobot2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_with(model: recipe, local: true) do |form| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :recipe_name %>
  </div>

  <div class="field">
    <%= form.label :process %>
    <%= form.text_area :process, id: :recipe_process %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url, id: :recipe_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recipes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Process</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= recipe.name %></td>
        <td><%= recipe.process %></td>
        <td><%= recipe.url %></td>
        <td><%= link_to 'Show', recipe %></td>
        <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
        <td><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipe', new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @recipe.name %>
</p>

<p>
  <strong>Process:</strong>
  <%= @recipe.process %>
</p>

<p>
  <strong>Url:</strong>
  <%= @recipe.url %>
</p>

<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>

app/views/usages/_form.html.erb
<%= form_with(model: usage, local: true) do |form| %>
  <% if usage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(usage.errors.count, "error") %> prohibited this usage from being saved:</h2>

      <ul>
      <% usage.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :recipe_id %>
    <%= form.number_field :recipe_id, id: :usage_recipe_id %>
  </div>

  <div class="field">
    <%= form.label :ingredient_id %>
    <%= form.number_field :ingredient_id, id: :usage_ingredient_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/usages/edit.html.erb
<h1>Editing Usage</h1>

<%= render 'form', usage: @usage %>

<%= link_to 'Show', @usage %> |
<%= link_to 'Back', usages_path %>

app/views/usages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Usages</h1>

<table>
  <thead>
    <tr>
      <th>Recipe</th>
      <th>Ingredient</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usages.each do |usage| %>
      <tr>
        <td><%= usage.recipe_id %></td>
        <td><%= usage.ingredient_id %></td>
        <td><%= link_to 'Show', usage %></td>
        <td><%= link_to 'Edit', edit_usage_path(usage) %></td>
        <td><%= link_to 'Destroy', usage, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Usage', new_usage_path %>

app/views/usages/new.html.erb
<h1>New Usage</h1>

<%= render 'form', usage: @usage %>

<%= link_to 'Back', usages_path %>

app/views/usages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Recipe:</strong>
  <%= @usage.recipe_id %>
</p>

<p>
  <strong>Ingredient:</strong>
  <%= @usage.ingredient_id %>
</p>

<%= link_to 'Edit', edit_usage_path(@usage) %> |
<%= link_to 'Back', usages_path %>